### ISSUE TITLE
Line annotations mess the editing layout

### ISSUE THREAD

**Issue by orenatol** [keanemind/jjk#9]
![Image](https://github.com/user-attachments/assets/0f421e0d-a53c-41cb-b1bf-18b542189f80)

VSCode:
Version: 1.97.2
Commit: e54c774e0add60467559eb0d1e229c6452cf8447
Date: 2025-02-12T23:20:35.343Z
Electron: 32.2.7
ElectronBuildId: 10982180
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

Jujutsu Kaizen: v0.5.2

**Comment by wesmoncrief** [comment]
Could we create a setting to disable the line annotations? I generally don't want to have these on

**Comment by Ralith** [comment]
+1 to a way to disable these. Aside from being unwanted to begin with, they also sometimes prompt the editor to scroll far to the right to accommodate them.

**Comment by kevin314** [comment]
Thanks for the screen recording! We'll look into what's causing this bug, but I think it's a good idea to add the option to disable annotations entirely as well. Thanks for the suggestions!

**Comment by kevin314** [comment]
The new release (0.6.0) adds a workspace setting `jjk.enableAnnotations` that you can disable to turn off annotations. We'll continue to look into why it's messing up the editor when it is turned on, though

**Comment by keanemind** [comment]
@orenatol this should be fixed in jjk v0.6.1

**Comment by alexbarton** [comment]
I'm still seeing this when using VIM mode with the "[vscodevim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)" extension:

Text is added after the in-line blame annotation and jumps back a short moment later. But this is really annoying, because the window even scrolls horizontally when the text in the line, plus the annotation text, is longer than the editor pane is wide …

jjk version 0.6.2, code version 1.100.2.

**Comment by Ghoughpteighbteau** [comment]
I personally would really really like to have the blame annotations but I am forced to have them off. I wonder if it's related to the size of the file?

https://github.com/user-attachments/assets/f5e29ceb-0854-465b-88ac-c7a3cd010c73
